### ISSUE TITLE
[React/이대호] 코드리뷰

### ISSUE THREAD

**Issue by BradDaehoLee** [synuns/toDoList#3]
와 정말 너무 잘 작성하셔서 놀랐습니다. ReadMe부터해서 mobile 화면까지 구현하시다니... 어나더 레벨이시네요.

제일 인상 깊었던건 컴포넌트 사용에대한 이해도가 매우 높으신것 같아요. 그중에서 Tooltip 컴포넌트가 제일 마음에 들었습니다. 

합성 컴포넌트라는 개념도 있는데 모르신다면 공부해보는것을 추천드려요.
https://fe-developers.kakaoent.com/2022/220731-composition-component/

프로젝트가 간단하기도했고, 잘 작성하셔서 조언드릴만한 내용이 크게 없는 것같네요. 
굳이 한 가지 조언을 드리자면 common 폴더에 있는 파일들도 결국 컴포넌트라고 볼 수있기 때문에 common 폴더를 component 폴더 안으로 이동시키는게 더 좋지 않을까 생각합니다.

**Comment by synuns** [comment]
합성 컴포넌트에 대한 글 너무 잘 읽었습니다.
컴포넌트 재사용성에 대한 고민이 많았는데 앞으로 프로젝트 진행하는 데 큰 도움이 될 것 같습니다.

common 폴더에 대한 부분은 component폴더 안으로 이동시켜서 수정했습니다
리뷰 감사드립니다!
